### ISSUE TITLE
:O

### ISSUE THREAD

**Issue by ghost** [77Z/SkittlesOS#1]
so cool!

**Comment by 77Z** [comment]
Thank you

This project is how I learned some C

**Comment by ghost** [comment]
:o woww, im learning assembly too, after i finish my little framework

**Comment by ghost** [comment]
do you have discord btw?

**Comment by 77Z** [comment]
Yeah, sorry for the late response, github doesn't send me notifications other then me checking manually

Temmie#7854

Super professional 👍

**Comment by ghost** [comment]
Lol no problem!

**Comment by ghost** [comment]
I sent a friend request btw :3
